[package]
name = "img2ascii"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "A simple command-line program to create ASCII art from a given image file"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
image = "0.25.5"
